#install.packages(c('stringr', 'data.table', 'lubridate', 'readr', 'dtplyr', 'tidyr', 'ggplot2', 'dplyr', 'magrittr'))
library(magrittr)
library(stringr)
library(data.table)
library(lubridate)
library(readr)
library(dtplyr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(magrittr)
library(zoo)
library(openxlsx)
